apiVersion: v2
name: gateway
description: Helm chart for deploying the agyn gateway service.
type: application
version: 0.4.1
appVersion: 0.4.0
home: https://github.com/agynio/gateway
sources:
  - https://github.com/agynio/gateway
dependencies:
  - name: service-base
    version: ">=0.1.4 <1.0.0"
    repository: oci://ghcr.io/agynio/charts
