// Package llmgen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package llmgen

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthMethod.
const (
	Bearer AuthMethod = "bearer"
)

// AuthMethod defines model for AuthMethod.
type AuthMethod string

// EntityMeta defines model for EntityMeta.
type EntityMeta struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	UpdatedAt *time.Time         `json:"updatedAt,omitempty"`
}

// LLMProvider defines model for LLMProvider.
type LLMProvider struct {
	AuthMethod AuthMethod         `json:"authMethod"`
	CreatedAt  time.Time          `json:"createdAt"`
	Endpoint   string             `json:"endpoint"`
	Id         openapi_types.UUID `json:"id"`
	UpdatedAt  *time.Time         `json:"updatedAt,omitempty"`
}

// LLMProviderCreateRequest defines model for LLMProviderCreateRequest.
type LLMProviderCreateRequest struct {
	AuthMethod AuthMethod `json:"authMethod"`
	Endpoint   string     `json:"endpoint"`
	Token      string     `json:"token"`
}

// LLMProviderUpdateRequest defines model for LLMProviderUpdateRequest.
type LLMProviderUpdateRequest struct {
	AuthMethod *AuthMethod `json:"authMethod,omitempty"`
	Endpoint   *string     `json:"endpoint,omitempty"`
	Token      *string     `json:"token,omitempty"`
}

// Model defines model for Model.
type Model struct {
	CreatedAt     time.Time          `json:"createdAt"`
	Id            openapi_types.UUID `json:"id"`
	LlmProviderId openapi_types.UUID `json:"llmProviderId"`
	Name          string             `json:"name"`
	RemoteName    string             `json:"remoteName"`
	UpdatedAt     *time.Time         `json:"updatedAt,omitempty"`
}

// ModelCreateRequest defines model for ModelCreateRequest.
type ModelCreateRequest struct {
	LlmProviderId openapi_types.UUID `json:"llmProviderId"`
	Name          string             `json:"name"`
	RemoteName    string             `json:"remoteName"`
}

// ModelUpdateRequest defines model for ModelUpdateRequest.
type ModelUpdateRequest struct {
	LlmProviderId *openapi_types.UUID `json:"llmProviderId,omitempty"`
	Name          *string             `json:"name,omitempty"`
	RemoteName    *string             `json:"remoteName,omitempty"`
}

// PaginatedLLMProviders defines model for PaginatedLLMProviders.
type PaginatedLLMProviders struct {
	Items   []LLMProvider `json:"items"`
	Page    int           `json:"page"`
	PerPage int           `json:"perPage"`
	Total   int           `json:"total"`
}

// PaginatedModels defines model for PaginatedModels.
type PaginatedModels struct {
	Items   []Model `json:"items"`
	Page    int     `json:"page"`
	PerPage int     `json:"perPage"`
	Total   int     `json:"total"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     *string `json:"type,omitempty"`
}

// IdPath defines model for IdPath.
type IdPath = openapi_types.UUID

// ProblemResponse defines model for ProblemResponse.
type ProblemResponse = Problem

// GetModelsParams defines parameters for GetModels.
type GetModelsParams struct {
	// ProviderId Filter by provider ID
	ProviderId *openapi_types.UUID `form:"providerId,omitempty" json:"providerId,omitempty"`
	Page       *int                `form:"page,omitempty" json:"page,omitempty"`
	PerPage    *int                `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// GetProvidersParams defines parameters for GetProviders.
type GetProvidersParams struct {
	Page    *int `form:"page,omitempty" json:"page,omitempty"`
	PerPage *int `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// PostResponsesJSONBody defines parameters for PostResponses.
type PostResponsesJSONBody struct {
	ModelId              openapi_types.UUID     `json:"model_id"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PostModelsJSONRequestBody defines body for PostModels for application/json ContentType.
type PostModelsJSONRequestBody = ModelCreateRequest

// PatchModelsIdJSONRequestBody defines body for PatchModelsId for application/json ContentType.
type PatchModelsIdJSONRequestBody = ModelUpdateRequest

// PostProvidersJSONRequestBody defines body for PostProviders for application/json ContentType.
type PostProvidersJSONRequestBody = LLMProviderCreateRequest

// PatchProvidersIdJSONRequestBody defines body for PatchProvidersId for application/json ContentType.
type PatchProvidersIdJSONRequestBody = LLMProviderUpdateRequest

// PostResponsesJSONRequestBody defines body for PostResponses for application/json ContentType.
type PostResponsesJSONRequestBody PostResponsesJSONBody

// Getter for additional properties for PostResponsesJSONBody. Returns the specified
// element and whether it was found
func (a PostResponsesJSONBody) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PostResponsesJSONBody
func (a *PostResponsesJSONBody) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PostResponsesJSONBody to handle AdditionalProperties
func (a *PostResponsesJSONBody) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["model_id"]; found {
		err = json.Unmarshal(raw, &a.ModelId)
		if err != nil {
			return fmt.Errorf("error reading 'model_id': %w", err)
		}
		delete(object, "model_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PostResponsesJSONBody to handle AdditionalProperties
func (a PostResponsesJSONBody) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["model_id"], err = json.Marshal(a.ModelId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'model_id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List LLM models
	// (GET /models)
	GetModels(w http.ResponseWriter, r *http.Request, params GetModelsParams)
	// Create LLM model
	// (POST /models)
	PostModels(w http.ResponseWriter, r *http.Request)
	// Delete LLM model
	// (DELETE /models/{id})
	DeleteModelsId(w http.ResponseWriter, r *http.Request, id IdPath)
	// Get LLM model by ID
	// (GET /models/{id})
	GetModelsId(w http.ResponseWriter, r *http.Request, id IdPath)
	// Update LLM model (partial)
	// (PATCH /models/{id})
	PatchModelsId(w http.ResponseWriter, r *http.Request, id IdPath)
	// List LLM providers
	// (GET /providers)
	GetProviders(w http.ResponseWriter, r *http.Request, params GetProvidersParams)
	// Create LLM provider
	// (POST /providers)
	PostProviders(w http.ResponseWriter, r *http.Request)
	// Delete LLM provider
	// (DELETE /providers/{id})
	DeleteProvidersId(w http.ResponseWriter, r *http.Request, id IdPath)
	// Get LLM provider by ID
	// (GET /providers/{id})
	GetProvidersId(w http.ResponseWriter, r *http.Request, id IdPath)
	// Update LLM provider (partial)
	// (PATCH /providers/{id})
	PatchProvidersId(w http.ResponseWriter, r *http.Request, id IdPath)
	// Proxy LLM response
	// (POST /responses)
	PostResponses(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List LLM models
// (GET /models)
func (_ Unimplemented) GetModels(w http.ResponseWriter, r *http.Request, params GetModelsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create LLM model
// (POST /models)
func (_ Unimplemented) PostModels(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete LLM model
// (DELETE /models/{id})
func (_ Unimplemented) DeleteModelsId(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get LLM model by ID
// (GET /models/{id})
func (_ Unimplemented) GetModelsId(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update LLM model (partial)
// (PATCH /models/{id})
func (_ Unimplemented) PatchModelsId(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List LLM providers
// (GET /providers)
func (_ Unimplemented) GetProviders(w http.ResponseWriter, r *http.Request, params GetProvidersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create LLM provider
// (POST /providers)
func (_ Unimplemented) PostProviders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete LLM provider
// (DELETE /providers/{id})
func (_ Unimplemented) DeleteProvidersId(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get LLM provider by ID
// (GET /providers/{id})
func (_ Unimplemented) GetProvidersId(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update LLM provider (partial)
// (PATCH /providers/{id})
func (_ Unimplemented) PatchProvidersId(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Proxy LLM response
// (POST /responses)
func (_ Unimplemented) PostResponses(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetModels operation middleware
func (siw *ServerInterfaceWrapper) GetModels(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetModelsParams

	// ------------- Optional query parameter "providerId" -------------

	err = runtime.BindQueryParameter("form", true, false, "providerId", r.URL.Query(), &params.ProviderId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerId", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameter("form", true, false, "perPage", r.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetModels(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostModels operation middleware
func (siw *ServerInterfaceWrapper) PostModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteModelsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteModelsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteModelsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetModelsId operation middleware
func (siw *ServerInterfaceWrapper) GetModelsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetModelsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchModelsId operation middleware
func (siw *ServerInterfaceWrapper) PatchModelsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchModelsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProviders operation middleware
func (siw *ServerInterfaceWrapper) GetProviders(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProvidersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameter("form", true, false, "perPage", r.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "perPage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProviders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostProviders operation middleware
func (siw *ServerInterfaceWrapper) PostProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProvidersId operation middleware
func (siw *ServerInterfaceWrapper) DeleteProvidersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProvidersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProvidersId operation middleware
func (siw *ServerInterfaceWrapper) GetProvidersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProvidersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchProvidersId operation middleware
func (siw *ServerInterfaceWrapper) PatchProvidersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchProvidersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostResponses operation middleware
func (siw *ServerInterfaceWrapper) PostResponses(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostResponses(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/models", wrapper.GetModels)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/models", wrapper.PostModels)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/models/{id}", wrapper.DeleteModelsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/models/{id}", wrapper.GetModelsId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/models/{id}", wrapper.PatchModelsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/providers", wrapper.GetProviders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/providers", wrapper.PostProviders)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/providers/{id}", wrapper.DeleteProvidersId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/providers/{id}", wrapper.GetProvidersId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/providers/{id}", wrapper.PatchProvidersId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/responses", wrapper.PostResponses)
	})

	return r
}

type ProblemResponseApplicationProblemPlusJSONResponse Problem

type GetModelsRequestObject struct {
	Params GetModelsParams
}

type GetModelsResponseObject interface {
	VisitGetModelsResponse(w http.ResponseWriter) error
}

type GetModels200JSONResponse PaginatedModels

func (response GetModels200JSONResponse) VisitGetModelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetModelsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetModelsdefaultApplicationProblemPlusJSONResponse) VisitGetModelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostModelsRequestObject struct {
	Body *PostModelsJSONRequestBody
}

type PostModelsResponseObject interface {
	VisitPostModelsResponse(w http.ResponseWriter) error
}

type PostModels201JSONResponse Model

func (response PostModels201JSONResponse) VisitPostModelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostModelsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostModelsdefaultApplicationProblemPlusJSONResponse) VisitPostModelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteModelsIdRequestObject struct {
	Id IdPath `json:"id"`
}

type DeleteModelsIdResponseObject interface {
	VisitDeleteModelsIdResponse(w http.ResponseWriter) error
}

type DeleteModelsId204Response struct {
}

func (response DeleteModelsId204Response) VisitDeleteModelsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteModelsIddefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteModelsIddefaultApplicationProblemPlusJSONResponse) VisitDeleteModelsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetModelsIdRequestObject struct {
	Id IdPath `json:"id"`
}

type GetModelsIdResponseObject interface {
	VisitGetModelsIdResponse(w http.ResponseWriter) error
}

type GetModelsId200JSONResponse Model

func (response GetModelsId200JSONResponse) VisitGetModelsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetModelsIddefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetModelsIddefaultApplicationProblemPlusJSONResponse) VisitGetModelsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PatchModelsIdRequestObject struct {
	Id   IdPath `json:"id"`
	Body *PatchModelsIdJSONRequestBody
}

type PatchModelsIdResponseObject interface {
	VisitPatchModelsIdResponse(w http.ResponseWriter) error
}

type PatchModelsId200JSONResponse Model

func (response PatchModelsId200JSONResponse) VisitPatchModelsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchModelsIddefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PatchModelsIddefaultApplicationProblemPlusJSONResponse) VisitPatchModelsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetProvidersRequestObject struct {
	Params GetProvidersParams
}

type GetProvidersResponseObject interface {
	VisitGetProvidersResponse(w http.ResponseWriter) error
}

type GetProviders200JSONResponse PaginatedLLMProviders

func (response GetProviders200JSONResponse) VisitGetProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProvidersdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetProvidersdefaultApplicationProblemPlusJSONResponse) VisitGetProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostProvidersRequestObject struct {
	Body *PostProvidersJSONRequestBody
}

type PostProvidersResponseObject interface {
	VisitPostProvidersResponse(w http.ResponseWriter) error
}

type PostProviders201JSONResponse LLMProvider

func (response PostProviders201JSONResponse) VisitPostProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostProvidersdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostProvidersdefaultApplicationProblemPlusJSONResponse) VisitPostProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteProvidersIdRequestObject struct {
	Id IdPath `json:"id"`
}

type DeleteProvidersIdResponseObject interface {
	VisitDeleteProvidersIdResponse(w http.ResponseWriter) error
}

type DeleteProvidersId204Response struct {
}

func (response DeleteProvidersId204Response) VisitDeleteProvidersIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProvidersIddefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteProvidersIddefaultApplicationProblemPlusJSONResponse) VisitDeleteProvidersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetProvidersIdRequestObject struct {
	Id IdPath `json:"id"`
}

type GetProvidersIdResponseObject interface {
	VisitGetProvidersIdResponse(w http.ResponseWriter) error
}

type GetProvidersId200JSONResponse LLMProvider

func (response GetProvidersId200JSONResponse) VisitGetProvidersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProvidersIddefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetProvidersIddefaultApplicationProblemPlusJSONResponse) VisitGetProvidersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PatchProvidersIdRequestObject struct {
	Id   IdPath `json:"id"`
	Body *PatchProvidersIdJSONRequestBody
}

type PatchProvidersIdResponseObject interface {
	VisitPatchProvidersIdResponse(w http.ResponseWriter) error
}

type PatchProvidersId200JSONResponse LLMProvider

func (response PatchProvidersId200JSONResponse) VisitPatchProvidersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchProvidersIddefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PatchProvidersIddefaultApplicationProblemPlusJSONResponse) VisitPatchProvidersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostResponsesRequestObject struct {
	Body *PostResponsesJSONRequestBody
}

type PostResponsesResponseObject interface {
	VisitPostResponsesResponse(w http.ResponseWriter) error
}

type PostResponses200JSONResponse map[string]interface{}

func (response PostResponses200JSONResponse) VisitPostResponsesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostResponses200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostResponses200TexteventStreamResponse) VisitPostResponsesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostResponsesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostResponsesdefaultApplicationProblemPlusJSONResponse) VisitPostResponsesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List LLM models
	// (GET /models)
	GetModels(ctx context.Context, request GetModelsRequestObject) (GetModelsResponseObject, error)
	// Create LLM model
	// (POST /models)
	PostModels(ctx context.Context, request PostModelsRequestObject) (PostModelsResponseObject, error)
	// Delete LLM model
	// (DELETE /models/{id})
	DeleteModelsId(ctx context.Context, request DeleteModelsIdRequestObject) (DeleteModelsIdResponseObject, error)
	// Get LLM model by ID
	// (GET /models/{id})
	GetModelsId(ctx context.Context, request GetModelsIdRequestObject) (GetModelsIdResponseObject, error)
	// Update LLM model (partial)
	// (PATCH /models/{id})
	PatchModelsId(ctx context.Context, request PatchModelsIdRequestObject) (PatchModelsIdResponseObject, error)
	// List LLM providers
	// (GET /providers)
	GetProviders(ctx context.Context, request GetProvidersRequestObject) (GetProvidersResponseObject, error)
	// Create LLM provider
	// (POST /providers)
	PostProviders(ctx context.Context, request PostProvidersRequestObject) (PostProvidersResponseObject, error)
	// Delete LLM provider
	// (DELETE /providers/{id})
	DeleteProvidersId(ctx context.Context, request DeleteProvidersIdRequestObject) (DeleteProvidersIdResponseObject, error)
	// Get LLM provider by ID
	// (GET /providers/{id})
	GetProvidersId(ctx context.Context, request GetProvidersIdRequestObject) (GetProvidersIdResponseObject, error)
	// Update LLM provider (partial)
	// (PATCH /providers/{id})
	PatchProvidersId(ctx context.Context, request PatchProvidersIdRequestObject) (PatchProvidersIdResponseObject, error)
	// Proxy LLM response
	// (POST /responses)
	PostResponses(ctx context.Context, request PostResponsesRequestObject) (PostResponsesResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetModels operation middleware
func (sh *strictHandler) GetModels(w http.ResponseWriter, r *http.Request, params GetModelsParams) {
	var request GetModelsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetModels(ctx, request.(GetModelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetModels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetModelsResponseObject); ok {
		if err := validResponse.VisitGetModelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostModels operation middleware
func (sh *strictHandler) PostModels(w http.ResponseWriter, r *http.Request) {
	var request PostModelsRequestObject

	var body PostModelsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostModels(ctx, request.(PostModelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostModels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostModelsResponseObject); ok {
		if err := validResponse.VisitPostModelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteModelsId operation middleware
func (sh *strictHandler) DeleteModelsId(w http.ResponseWriter, r *http.Request, id IdPath) {
	var request DeleteModelsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteModelsId(ctx, request.(DeleteModelsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteModelsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteModelsIdResponseObject); ok {
		if err := validResponse.VisitDeleteModelsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetModelsId operation middleware
func (sh *strictHandler) GetModelsId(w http.ResponseWriter, r *http.Request, id IdPath) {
	var request GetModelsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetModelsId(ctx, request.(GetModelsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetModelsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetModelsIdResponseObject); ok {
		if err := validResponse.VisitGetModelsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchModelsId operation middleware
func (sh *strictHandler) PatchModelsId(w http.ResponseWriter, r *http.Request, id IdPath) {
	var request PatchModelsIdRequestObject

	request.Id = id

	var body PatchModelsIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchModelsId(ctx, request.(PatchModelsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchModelsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchModelsIdResponseObject); ok {
		if err := validResponse.VisitPatchModelsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProviders operation middleware
func (sh *strictHandler) GetProviders(w http.ResponseWriter, r *http.Request, params GetProvidersParams) {
	var request GetProvidersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProviders(ctx, request.(GetProvidersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProviders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProvidersResponseObject); ok {
		if err := validResponse.VisitGetProvidersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostProviders operation middleware
func (sh *strictHandler) PostProviders(w http.ResponseWriter, r *http.Request) {
	var request PostProvidersRequestObject

	var body PostProvidersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostProviders(ctx, request.(PostProvidersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostProviders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostProvidersResponseObject); ok {
		if err := validResponse.VisitPostProvidersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteProvidersId operation middleware
func (sh *strictHandler) DeleteProvidersId(w http.ResponseWriter, r *http.Request, id IdPath) {
	var request DeleteProvidersIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProvidersId(ctx, request.(DeleteProvidersIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProvidersId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteProvidersIdResponseObject); ok {
		if err := validResponse.VisitDeleteProvidersIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProvidersId operation middleware
func (sh *strictHandler) GetProvidersId(w http.ResponseWriter, r *http.Request, id IdPath) {
	var request GetProvidersIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProvidersId(ctx, request.(GetProvidersIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProvidersId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProvidersIdResponseObject); ok {
		if err := validResponse.VisitGetProvidersIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchProvidersId operation middleware
func (sh *strictHandler) PatchProvidersId(w http.ResponseWriter, r *http.Request, id IdPath) {
	var request PatchProvidersIdRequestObject

	request.Id = id

	var body PatchProvidersIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchProvidersId(ctx, request.(PatchProvidersIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchProvidersId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchProvidersIdResponseObject); ok {
		if err := validResponse.VisitPatchProvidersIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostResponses operation middleware
func (sh *strictHandler) PostResponses(w http.ResponseWriter, r *http.Request) {
	var request PostResponsesRequestObject

	var body PostResponsesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostResponses(ctx, request.(PostResponsesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostResponses")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostResponsesResponseObject); ok {
		if err := validResponse.VisitPostResponsesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
